<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>A2dpSink</RootNamespace>
    <AssemblyName>C4P</AssemblyName>
    <AssemblyTitle>C4P</AssemblyTitle>
    <Product>C4P</Product>
    <Company>C4P</Company>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWinRT>true</UseWinRT>
    <ApplicationIcon>AppIcon.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="AppIcon.ico" />
  </ItemGroup>

</Project>
